name: run tests
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: blazemeter_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get version
        id: version
        run: echo "dsl_version=0.52" >> $GITHUB_ENV
      - name: Deploy github pages
        run: .github/vuepress-deploy.sh
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: abstracta/jmeter-java-dsl-sample
          path: jmeter-java-dsl-sample
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: update version in sample project
        run: .github/update-sample-version.sh ${{ env.dsl_version }}
